version: '3.8'

services:
  webhook-service:
    build: .
    container_name: github-webhook-service
    ports:
      - "4044:4044"
    environment:
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
      - PORT=4044
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-false}
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - ./config:/app/config:ro
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4044/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s